server:
  port: 7001

spring:
  application:
    name: pos-discovery

#配置单节点 eureka 服务器
eureka:
  instance:
    instance-id: pos-discovery7001
    prefer-ip-address: true
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:7001/eureka
