server:
  port: 8001

spring:
  application:
    name: pos-products
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
  datasource:
    url: jdbc:mysql://localhost:23306/aw06_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: $2a$10$1P5vApro6CGetwiQYGSxF.719D2qz/nbFM8FQpP59dJi85Q/p5n6m

eureka:
  instance:
    instance-id: pos-products8001
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7001/eureka

resilience4j:
  circuitbreaker:
    instances:
      # 可用的配置参数参考 -- https://resilience4j.readme.io/docs/circuitbreaker
      product-controller:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        slowCallDurationThreshold: 1000ms
        slowCallRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 10
        automaticTransitionFromOpenToHalfOpenEnabled: true

mybatis:
  mapper-locations: classpath:mybatis/*.xml
  type-aliases-package: com.micropos.products.model
  type-handlers-package: com.micropos.products.model
  configuration:
    jdbc-type-for-null: null
