server:
  port: 8001

spring:
  application:
    name: pos-products
  cache:
    type: redis
  redis:
    password: Saw0rk_2o22
    cluster:
      nodes: 124.222.168.27:6379,124.222.168.27:6380,124.222.168.27:6381,124.222.168.27:6382,124.222.168.27:6383,124.222.168.27:6384
      max-redirects: 6
  datasource:
    url: jdbc:mysql://124.222.168.27:3306/aw06_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Saw0rk_2o22

eureka:
  instance:
    instance-id: pos-products8001
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7001/eureka

resilience4j:
  circuitbreaker:
    instances:
      # 可用的配置参数参考 -- https://resilience4j.readme.io/docs/circuitbreaker
      product-controller:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        slowCallDurationThreshold: 1000ms
        slowCallRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 10
        automaticTransitionFromOpenToHalfOpenEnabled: true

mybatis:
  mapper-locations: classpath:mybatis/*.xml
  type-aliases-package: com.micropos.products.model
  type-handlers-package: com.micropos.products.model
  configuration:
    jdbc-type-for-null: null
