server:
  port: 11001

spring:
  application:
    name: pos-orders
  rabbitmq:
    host: 124.222.168.27
    port: 5672
    username: root
    password: Saw0rk_2o22
  data:
    mongodb:
      host: 124.222.168.27
      port: 27017
      username: root
      password: Saw0rk_2o22
  redis:
    password: Saw0rk_2o22
    cluster:
      nodes: 124.222.168.27:6379,124.222.168.27:6380,124.222.168.27:6381,124.222.168.27:6382,124.222.168.27:6383,124.222.168.27:6384
      max-redirects: 6
  session:
    store-type: redis
  cloud:
    function:
      definition: # ok
    stream:
      bindings:
        order-out-0:
          binder: rabbit
          destination: orderExchange
          group: default

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7001/eureka
