server:
  port: 8080

spring:
  application:
    name: pos-gateway
  web:
    resources:
      static-locations:
        - classpath:/META-INF/resources/
        - classpath:/resources/
        - classpath:/static/
        - classpath:/public/
        - classpath:/build/
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: pos-products
          uri: lb://pos-products
          predicates:
            - Path=/api/products/**

        - id: pos-carts
          uri: lb://pos-carts
          predicates:
            - Path=/api/carts/**

        - id: pos-orders
          uri: lb://pos-orders
          predicates:
            - Path=/api/orders/**

eureka:
  instance:
    instance-id: pos-gateway8080
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7001/eureka
