server:
  port: 12001

spring:
  application:
    name: pos-delivery
  rabbitmq:
    host: 124.222.168.27
    port: 5672
    username: root
    password: Saw0rk_2o22
  data:
    mongodb:
      host: 124.222.168.27
      port: 27017
      username: root
      password: Saw0rk_2o22
  cloud:
    function:
      definition: order;phaseSupplier;phaseConsumer
    stream:
      bindings:
        order-in-0:
          binder: rabbit
          destination: orderExchange
          group: default
        phaseSupplier-out-0:
          binder: rabbit
          destination: phaseExchange
          group: default
        phaseConsumer-in-0:
          binder: rabbit
          destination: phaseExchange
          group: default
      poller:
        fixed-delay: 10000
